/**
 * Capabilities deck — designed full-screen build.
 *
 * Emits Capabilities/index.html from the DATA model below. Content mirrors the
 * master PPTX ("XYZStudios - Capabilities Deck"); media files live in
 * Capabilities/deck-media (generated by scripts/build-deck-from-pptx.mjs).
 *
 * Usage: node scripts/build-deck.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'Capabilities', 'index.html');
const M = 'deck-media';

// ---------------------------------------------------------------------------
// DATA — one entry per slide. `chapter` feeds the HUD label.
// ---------------------------------------------------------------------------

const DATA = [
  { type: 'cover', chapter: 'Capabilities' },
  {
    type: 'about', chapter: 'About', nav: 'About',
    image: 'image-3-2.jpg',
    lead: 'A post-production studio built through close creative collaboration.',
    body: ['Working with production teams, agencies, and directors to carry projects through post, supporting where needed and staying closely involved through final delivery.', 'Each project evolves differently, and the approach is shaped to serve the work and its intended outcome.'],
  },
  {
    type: 'wall', chapter: 'Highlighted Work', nav: 'Highlighted Work',
    images: ['image-4-7.jpg', 'image-4-2.jpg', 'image-4-4.jpg', 'image-4-5.jpg', 'image-4-9.jpg', 'image-4-10.jpg', 'image-4-3.jpg', 'image-4-1.jpg', 'image-4-6.jpg'],
  },
  { type: 'divider', chapter: 'Craft', nav: 'Craft', no: '01', title: 'Craft', image: 'image-23-2.jpg' },
  {
    type: 'craft', chapter: 'Craft',
    title: 'Creative Development',
    body: 'Visual direction, structure, and shot logic are established before production begins. Storyboards and early visual exploration define composition, pacing, and technical feasibility, ensuring clarity across production and post.',
    layout: 'hero-grid', images: ['image-24-2.jpg', 'image-24-5.jpg', 'image-24-4.jpg', 'image-24-6.jpg', 'image-24-7.jpg', 'image-24-9.jpg', 'image-24-8.jpg'],
  },
  {
    type: 'craft', chapter: 'Craft',
    title: 'CG Integration',
    body: 'CG elements are embedded into live-action plates using accurate camera tracking, lens calibration, and scene lighting. Surface interaction, shadow behavior, and material response are refined to ensure consistency across motion, grading, and final delivery.',
    layout: 'row', images: ['image-25-4.jpg', 'image-25-2.jpg', 'image-25-3.jpg'],
  },
  {
    type: 'craft', chapter: 'Craft',
    title: 'CG Environments',
    body: 'At any scale, from full digital builds to set extensions and enhancements. We recreate real locations or design new spaces to match the project’s tone, with careful attention to scale, lighting, perspective, and atmosphere. Every environment is built for seamless integration across the sequence.',
    layout: 'row', images: ['image-26-2.jpg', 'image-26-4.jpg', 'image-26-3.jpg'],
  },
  {
    type: 'craft', chapter: 'Craft',
    title: 'Compositing',
    body: 'Live-action and rendered elements are unified through precise control of depth, exposure, color space, and optical response. Integration is refined at the pixel level to ensure visual continuity across the entire sequence.',
    layout: 'hero-grid', images: ['image-27-4.jpg', 'image-27-2.jpg', 'image-27-7.jpg', 'image-27-6.jpg', 'image-27-5.jpg'],
  },
  {
    type: 'craft', chapter: 'Craft',
    title: 'Simulation and FX',
    body: 'Physical motion and environmental interaction are developed using accurate scale, timing, and force behavior. Simulations are refined to respond naturally within the scene and remain consistent across camera perspective and integration.',
    layout: 'hero-grid', images: ['image-28-4.jpg', 'image-28-8.jpg', 'image-28-5.jpg', 'image-28-3.jpg', 'image-28-6.jpg'],
  },
  {
    type: 'craft', chapter: 'Craft',
    title: 'Polish',
    body: 'Cleanup, beauty work, and set extensions as part of finishing, refining continuity and removing distractions that pull focus. From subtle fixes to larger extensions, the result is a clean, cohesive finish that holds up across the sequence and delivers to spec.',
    layout: 'grid6', images: ['image-29-7.jpg', 'image-29-4.jpg', 'image-29-5.jpg', 'image-29-6.jpg', 'image-29-2.jpg', 'image-29-3.jpg'],
  },
  {
    type: 'craft', chapter: 'Craft',
    title: 'AI-Assisted Workflow',
    body: 'We integrate AI into live-action and CG workflows as a controlled extension of our process. It allows us to explore, iterate, and build imagery that would otherwise be difficult or time-intensive, while keeping every decision guided by artists. AI remains a tool, supporting realism, precision, and creative intent, never replacing it.',
    layout: 'hero-grid', images: ['image-31-2.jpg', 'image-31-4.jpg', 'image-31-3.jpg'],
  },
  { type: 'divider', chapter: 'Full Production', nav: 'Full Production', no: '02', title: 'Full Production', image: 'image-6-1.webp' },
  {
    type: 'project', chapter: 'Full Production',
    client: 'Salomon', title: 'Speedcross 6', year: '2026', bg: 'image-7-2.jpg',
    director: 'Lenn Anton',
    scope: ['Concept to Final Delivery', 'Creative Direction', 'Production', 'VFX', 'CG', 'AI', 'Compositing', 'Editing', 'Sound Design & Mix'],
    build: [['60%', 'Live Action'], ['33%', 'AI'], ['7%', 'CGI']],
    output: [['214', 'Final Frames'], ['2', 'Hero Shots']],
  },
  {
    type: 'project', chapter: 'Full Production',
    client: 'Atomic', title: 'Into The Void', year: '2026', bg: 'image-8-3.jpg',
    director: 'Dris Yousif', note: 'Concept Piece',
    scope: ['Concept to Final Delivery', 'Creative Direction', 'Production', 'CG', 'Simulation', 'Compositing', 'Editing', 'Sound Design & Mix'],
    build: [['92%', 'CG'], ['8%', 'AI'], ['1', 'Environment']],
    output: [['1400', 'Final Frames'], ['10', 'Hero Shots']],
  },
  {
    type: 'project', chapter: 'Full Production',
    client: 'Rory McIlroy', title: 'RBC Canadian Open', year: '2025', bg: 'image-9-2.jpg',
    director: 'Samry Yussuf',
    scope: ['Concept to Final Delivery', 'Creative Direction', 'Production', 'VFX', 'CG', 'Compositing', 'Editing', 'Sound Design & Mix'],
    build: [['72%', 'CG'], ['20%', 'Motion Graphics'], ['7%', 'Live Action']],
    output: [['1009', 'Final Frames'], ['8', 'Hero Shots'], ['4', 'Environments']],
  },
  { type: 'divider', chapter: 'Case Study', nav: 'Case Study', no: '03', title: 'Case Studies', image: 'image-10-1.webp' },
  {
    type: 'case', chapter: 'Case Study — RBC Canadian Open',
    step: '01', title: 'Storyboard', meta: 'Rory McIlroy — RBC Canadian Open',
    body: ['With no live shoot possible, the client asked us to develop the creative direction and bring the concept to life.', 'We crafted a stylized 3D hype reel, taking the project from concept art through to final execution. Throughout the process, the client remained closely involved, providing notes and feedback as we shaped the visuals to capture Rory’s momentum and the anticipation around the tournament.'],
    layout: 'duo-wide', images: ['image-11-2.webp', 'image-11-3.jpg'],
  },
  {
    type: 'case', chapter: 'Case Study — RBC Canadian Open',
    step: '02', title: 'Pre-visualization', meta: 'Rory McIlroy — RBC Canadian Open',
    body: ['Before moving into final production, we built a full pre-vis to map out pacing, camera moves, and overall flow. This stage gave the client a clear first look at how the story would unfold on screen.', 'By reviewing timing, framing, and energy early on, they were able to provide detailed notes and shape the direction with us. The pre-vis ensured everyone was aligned creatively before resources went into final rendering and polish.'],
    layout: 'hero-grid', images: ['image-12-2.jpg', 'image-12-4.jpg', 'image-12-3.jpg', 'image-12-5.jpg', 'image-12-6.jpg'],
  },
  {
    type: 'case', chapter: 'Case Study — RBC Canadian Open',
    step: '03', title: 'Asset Prep', meta: 'Rory McIlroy — RBC Canadian Open',
    body: ['The client asked that specific elements be featured within the reel to tie back to Rory and the tournament.', 'We developed 3D assets for the Osprey bird (a nod to the course), Rory’s championship ring, the custom Rory gold ball, and the RBC Canadian Open trophy. Each was designed and integrated to enhance the narrative while aligning with the overall creative direction.'],
    layout: 'strip', images: ['image-13-2.jpg', 'image-13-5.jpg', 'image-13-6.webp', 'image-13-3.jpg', 'image-13-4.jpg'],
  },
  {
    type: 'case', chapter: 'Case Study — RBC Canadian Open',
    step: '04', title: 'Environment', meta: 'Rory McIlroy — RBC Canadian Open',
    body: ['Since no shoot was possible, we relied on archival footage of Rory and rebuilt the tournament setting digitally.', 'Using detailed golf course maps as a base, we laid out and modeled the landscapes of Osprey Valley. From there, we re-created and enhanced the textures, rebuilt surfaces, and scattered nature elements to bring the environments to life. The result was a set of realistic, fully CG environments that replicated the real course while still supporting the stylized, cinematic direction of the reel.'],
    layout: 'hero-grid', images: ['image-14-6.jpg', 'image-14-2.jpg', 'image-14-4.jpg', 'image-14-3.jpg'],
  },
  {
    type: 'case', chapter: 'Case Study — RBC Canadian Open',
    step: '05', title: 'Reference', meta: 'Rory McIlroy — RBC Canadian Open',
    body: ['The client provided detailed references of Osprey Valley, which we used as the foundation for the build.', 'These materials ensured the environments were accurate to the real course and helped us deliver a CG space that feels authentic and true to the tournament setting.'],
    layout: 'hero-grid', images: ['image-15-8.jpg', 'image-15-2.jpg', 'image-15-3.jpg', 'image-15-4.jpg', 'image-15-7.jpg', 'image-15-6.jpg', 'image-15-5.jpg'],
  },
  {
    type: 'case', chapter: 'Case Study — Celsius',
    step: '01', title: 'On Location References', meta: 'Celsius — Spritz Vibe',
    body: [],
    layout: 'mosaic', images: ['image-17-3.jpg', 'image-17-2.jpg', 'image-17-11.jpg', 'image-17-1.jpg', 'image-17-5.jpg', 'image-17-6.jpg', 'image-17-8.jpg', 'image-17-10.jpg', 'image-17-9.jpg'],
  },
  {
    type: 'case', chapter: 'Case Study — Celsius',
    step: '02', title: 'Live Action Plate', meta: 'Celsius — Spritz Vibe',
    body: [],
    layout: 'duo', images: ['image-18-3.jpg', 'image-18-2.jpg'],
  },
  {
    type: 'project', chapter: 'Case Study',
    client: 'Celsius', title: 'Spritz Vibe', year: '2025', bg: 'image-16-3.jpg',
    scope: ['Pre-Production', 'VFX', 'CG', 'Simulation', 'Clean Up', 'Compositing', 'Sound Design & Mix'],
    build: [['60%', 'Live Action'], ['40%', 'CG'], ['1', 'Environment']],
    output: [['992', 'Final Frames'], ['8', 'Hero Shots']],
  },
  {
    type: 'how', chapter: 'How We Work', nav: 'How We Work',
    title: 'How We Work',
    image: 'image-33-3.webp',
    items: [
      'Each collaboration begins with alignment and develops through shared intent and consistent execution.',
      'Our involvement adapts to the needs of each project.',
      'Some collaborations last a single project. Others continue for years.',
    ],
  },
  {
    type: 'contact', chapter: 'Contact', nav: 'Contact',
    image: 'image-34-2.jpg',
    people: [
      ['Samry Yussuf', 'Post Producer, Co-Founder', 'Samry@xyzstudios.co'],
      ['Dris Yousif', 'Post Producer, Co-Founder', 'Dris@xyzstudios.co'],
    ],
    links: [
      ['Email', 'mailto:Inquiries@xyzstudios.co', 'Inquiries@xyzstudios.co'],
      ['Website', 'https://xyzstudios.co', 'xyzstudios.co'],
      ['Instagram', 'https://www.instagram.com/xyz__studios/', '@xyz__studios'],
      ['LinkedIn', 'https://www.linkedin.com/company/xyzstudioss/', 'XYZ Studios'],
    ],
  },
];

// ---------------------------------------------------------------------------
// templates
// ---------------------------------------------------------------------------

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const img = (file, cls = '', eager = false) =>
  `<img class="${cls}" src="${M}/${file}" alt="" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} draggable="false">`;
/** Split heading into masked reveal lines */
const lines = (text, cls = '') =>
  `<span class="rl ${cls}"><span class="rl-i">${esc(text)}</span></span>`;

function tCover() {
  return `
  <div class="sl-cover">
    <div class="cover-bg">${img('cover-strip.jpg', 'cover-horse', true)}</div>
    <div class="cover-shade"></div>
    <div class="cover-year" aria-hidden="true">2026</div>
    <div class="cover-inner">
      <div class="cover-kicker"><span class="mono">International creative post production studio</span><span class="mono">Inquiries@xyzstudios.co</span></div>
      <h1 class="cover-title">${lines('Capabilities')}${lines('Deck — 2026', 'cover-sub')}</h1>
      <div class="cover-foot mono"><span>XYZSTUDIOS &copy; 2026</span><span>VFX &middot; CG &middot; Sound</span></div>
    </div>
  </div>`;
}

function tToc(d) {
  const items = d.items || [];
  const rows = items
    .map(
      ([label, slide], i) => `
      <button class="toc-row" data-goto="${slide}">
        <span class="mono toc-no">${String(i + 1).padStart(2, '0')}</span>
        <span class="toc-label">${esc(label)}</span>
        <span class="mono toc-pg">${String(slide).padStart(2, '0')}</span>
      </button>`
    )
    .join('');
  return `
  <div class="sl-toc">
    <h2 class="toc-title">${lines('Index')}</h2>
    <div class="toc-list">${rows}</div>
  </div>`;
}

function tAbout(d) {
  return `
  <div class="sl-about">
    <div class="about-media">${img(d.image, 'fill')}</div>
    <div class="about-copy">
      <div class="mono lbl">About</div>
      <h2 class="about-lead">${lines(d.lead)}</h2>
      ${d.body.map((p) => `<p class="body">${esc(p)}</p>`).join('')}
    </div>
  </div>`;
}

function tWall(d) {
  return `
  <div class="sl-wall">
    <div class="wall-grid">${d.images.map((f) => `<div class="wall-cell">${img(f, 'fill')}</div>`).join('')}</div>
    <div class="wall-cap mono"><span>Highlighted Work</span><span>2024 — 2026</span></div>
  </div>`;
}

function tServices(d) {
  const cells = d.items
    .map(
      ([t, b], i) => `
      <div class="svc">
        <div class="mono svc-no">${String(i + 1).padStart(2, '0')}</div>
        <div class="svc-t">${esc(t)}</div>
        <p class="svc-b">${esc(b)}</p>
      </div>`
    )
    .join('');
  return `
  <div class="sl-services">
    <h2 class="svc-title">${lines('What We Do')}</h2>
    <div class="svc-grid">${cells}</div>
  </div>`;
}

function tDivider(d) {
  return `
  <div class="sl-divider">
    <div class="div-media">${img(d.image, 'fill')}</div>
    <div class="div-shade"></div>
    <div class="div-copy">
      <div class="div-no mono">Chapter ${d.no}</div>
      <h2 class="div-title">${lines(d.title)}</h2>
    </div>
  </div>`;
}

function tProject(d) {
  const scope = d.scope.map((s) => `<li>${esc(s)}</li>`).join('');
  const build = d.build
    .map(([v, l]) => `<div class="stat"><span class="stat-v" data-count="${esc(v)}">${esc(v)}</span><span class="mono stat-l">${esc(l)}</span></div>`)
    .join('');
  const output = d.output
    .map(([v, l]) => `<div class="stat"><span class="stat-v" data-count="${esc(v)}">${esc(v)}</span><span class="mono stat-l">${esc(l)}</span></div>`)
    .join('');
  return `
  <div class="sl-project">
    <div class="prj-media">${img(d.bg, 'fill')}</div>
    <div class="prj-grade"></div>
    <div class="prj-inner">
      <div class="prj-top">
        <div><div class="mono lbl">Client</div><div class="prj-client">${esc(d.client)}</div></div>
        ${d.director ? `<div><div class="mono lbl">Director</div><div class="prj-client">${esc(d.director)}</div></div>` : ''}
        ${d.note ? `<div><div class="mono lbl">Type</div><div class="prj-client">${esc(d.note)}</div></div>` : ''}
        <div><div class="mono lbl">Year</div><div class="prj-client">${esc(d.year)}</div></div>
      </div>
      <h2 class="prj-title">${lines(d.title)}</h2>
      <div class="prj-bottom">
        <div class="prj-scope"><div class="mono lbl">Scope</div><ul>${scope}</ul></div>
        <div class="prj-stats">
          <div class="prj-statgroup"><div class="mono lbl">Build</div><div class="stat-row">${build}</div></div>
          <div class="prj-statgroup"><div class="mono lbl">Output</div><div class="stat-row">${output}</div></div>
        </div>
      </div>
    </div>
  </div>`;
}

function metaLines(meta) {
  return String(meta)
    .split(/\s*[—–-]\s*/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function caseImages(layout, images) {
  if (layout === 'duo' || layout === 'duo-wide') {
    return `<div class="cs-media cs-duo${layout === 'duo-wide' ? ' wide' : ''}">${images.map((f) => `<div class="cs-cell">${img(f, 'fill')}</div>`).join('')}</div>`;
  }
  if (layout === 'strip') {
    return `<div class="cs-media cs-strip">${images.map((f) => `<div class="cs-cell">${img(f, 'fill')}</div>`).join('')}</div>`;
  }
  if (layout === 'mosaic') {
    return `<div class="cs-media cs-mosaic">${images.map((f) => `<div class="cs-cell">${img(f, 'fill')}</div>`).join('')}</div>`;
  }
  const [first, ...rest] = images;
  if (rest.length === 3) {
    const [a, b, c] = rest;
    return `<div class="cs-media cs-ppt-grid">
      <div class="cs-ppt-big cs-cell">${img(first, 'fill')}</div>
      <div class="cs-ppt-mt cs-cell">${img(a, 'fill')}</div>
      <div class="cs-ppt-mb cs-cell">${img(b, 'fill')}</div>
      <div class="cs-ppt-tall cs-cell">${img(c, 'fill')}</div>
    </div>`;
  }
  return `<div class="cs-media cs-hero"><div class="cs-cell cs-big">${img(first, 'fill')}</div><div class="cs-rest n${rest.length}">${rest.map((f) => `<div class="cs-cell">${img(f, 'fill')}</div>`).join('')}</div></div>`;
}

function tCase(d) {
  const meta = metaLines(d.meta);
  return `
  <div class="sl-case">
    <div class="cs-head-ppt">
      <h2 class="cs-title">${esc(d.title)}</h2>
      <div class="cs-meta-col">${meta.map((line) => `<div class="cs-meta">${esc(line)}</div>`).join('')}</div>
      ${d.body.length ? `<div class="cs-copy">${d.body.map((p) => `<p class="body">${esc(p)}</p>`).join('')}</div>` : ''}
    </div>
    ${caseImages(d.layout, d.images)}
  </div>`;
}

function tCraft(d) {
  let media;
  if (d.layout === 'row') {
    media = `<div class="cs-media cs-strip">${d.images.map((f) => `<div class="cs-cell">${img(f, 'fill')}</div>`).join('')}</div>`;
  } else if (d.layout === 'grid6') {
    media = `<div class="cs-media cs-grid6">${d.images.map((f) => `<div class="cs-cell">${img(f, 'fill')}</div>`).join('')}</div>`;
  } else {
    media = caseImages('hero-grid', d.images);
  }
  return `
  <div class="sl-case sl-craft">
    <div class="cs-head-ppt">
      <div class="mono cs-craft-lbl">Craft</div>
      <h2 class="cs-title">${esc(d.title)}</h2>
      <div class="cs-copy"><p class="body">${esc(d.body)}</p></div>
    </div>
    ${media}
  </div>`;
}

function tFocus(d) {
  return `
  <div class="sl-focus">
    <h2 class="cs-title">${lines(d.title)}</h2>
    <div class="focus-strip">
      ${d.images
        .map(
          ([f, label], i) => `
        <figure class="focus-cell">
          ${img(f, 'fill')}
          <figcaption class="mono"><span>${String(i + 1).padStart(2, '0')}</span>${esc(label)}</figcaption>
        </figure>`
        )
        .join('')}
    </div>
    <p class="body focus-cap">${esc(d.body)}</p>
  </div>`;
}

function tHow(d) {
  return `
  <div class="sl-how">
    <div class="how-media">${img(d.image, 'fill')}</div>
    <div class="how-copy">
      <h2 class="cs-title">${esc(d.title)}</h2>
      <div class="how-list">
        ${d.items.map((t, i) => `<div class="how-row"><span class="mono">${String(i + 1).padStart(2, '0')}</span><p>${esc(t)}</p></div>`).join('')}
      </div>
    </div>
  </div>`;
}

function tContact(d) {
  return `
  <div class="sl-contact">
    <h2 class="contact-title">${lines('Let’s Build')}${lines('Something Real')}</h2>
    <div class="contact-grid">
      <div class="contact-people">
        ${d.people.map(([n, r, e]) => `<div class="person"><div class="person-n">${esc(n)}</div><div class="mono person-r">${esc(r)}</div><a class="person-e" href="mailto:${esc(e)}">${esc(e)}</a></div>`).join('')}
      </div>
      <div class="contact-links">
        ${d.links.map(([l, href, t]) => `<a class="clink" href="${esc(href)}" target="_blank" rel="noopener"><span class="mono lbl">${esc(l)}</span><span>${esc(t)}</span></a>`).join('')}
      </div>
      <div class="contact-media">${img(d.image, 'fill')}</div>
    </div>
    <div class="contact-foot mono"><span>XYZSTUDIOS &copy; 2026</span><span>International creative post production studio</span></div>
  </div>`;
}

const TEMPLATES = {
  cover: tCover, toc: tToc, about: tAbout, wall: tWall, services: tServices,
  divider: tDivider, project: tProject, case: tCase, craft: tCraft,
  focus: tFocus, how: tHow, contact: tContact,
};

// ---------------------------------------------------------------------------

const BLEED = new Set(['cover', 'divider', 'project', 'wall']);

const slidesHtml = DATA.map((d, i) => {
  const inner = TEMPLATES[d.type](d);
  const cls = BLEED.has(d.type) ? 'slide slide--bleed' : 'slide slide--inset';
  return `<section class="${cls}" data-chapter="${esc(d.chapter)}" data-i="${i}">${inner}</section>`;
}).join('\n');

const html = fs
  .readFileSync(path.join(__dirname, 'deck-shell.html'), 'utf8')
  .replace('<!--SLIDES-->', slidesHtml)
  .replace(/__TOTAL__/g, String(DATA.length));

fs.writeFileSync(OUT, html, 'utf8');
console.log(`Wrote ${OUT} — ${DATA.length} slides`);
